### ISSUE TITLE
MapContainer does not cleanup when unmounted

### ISSUE THREAD

**Issue by tbowmo** [PaulLeCam/react-leaflet#1001]
## Bug report in v4

**Before** opening an issue, make sure to read the [contributing guide](https://github.com/PaulLeCam/react-leaflet/blob/master/CONTRIBUTING.md) and understand this is a bug tracker, not a support platform.

Please make sure to check the following boxes before submitting an issue.\
**Issues opened without using this template will be closed unless they have a good reason not to follow this template.**

- [x] All peer dependencies are installed: React, ReactDOM and Leaflet.
- [x] Using the latest version of React and ReactDOM v18.
- [x] Using the supported version of Leaflet (v1.8.0 minimum) and its corresponding CSS file is loaded.
- [x] Using the [latest v4 version of React-Leaflet](https://github.com/PaulLeCam/react-leaflet/releases).
- [x] The issue has not already been reported.
- [x] Make sure you have followed the [quick start guide](https://leafletjs.com/examples/quick-start.html) for Leaflet.
- [x] Make sure you have fully read the [documentation](https://react-leaflet.js.org/docs/start-introduction) and that you understand the [limitations](https://react-leaflet.js.org/docs/start-introduction#limitations).

### Expected behavior

React-leaflet cleans up the leaflet-map container when MapContainer is unmounted.

### Actual behavior

While debugging an error in my site with "Map container is already initialized", I went through the code of React-Leaflet, and in particular MapContainer.

MapContainer tries to remove the leaflet map [here](https://github.com/PaulLeCam/react-leaflet/blob/0566183ef3e6e4861e8636add11d2e20d730b608/packages/react-leaflet/src/MapContainer.tsx#L73), I tried inserting a console.log, writing out the content of `context`, this is always undefined in my case, so it never calls `map.remove()` to remove the map when the component is unmounted.

While debugging, I also placed a simple console.log('here') inside the [mapRef useCallback](https://github.com/PaulLeCam/react-leaflet/blob/0566183ef3e6e4861e8636add11d2e20d730b608/packages/react-leaflet/src/MapContainer.tsx#L56) method, just before `if`, and it is never executed (console.log is never written)

**Comment by Lowentwickler** [comment]
If I understand right, as a result of this, I have `fullscreencontrol` duplicated on every re-draw

**Comment by PaulLeCam** [comment]
Indeed the context wasn't captured, it should be fixed in v4.0.1, please try it out!

**Comment by Lowentwickler** [comment]
@PaulLeCam It seems that external controls are not being removed from the map on component redraw still.

**Comment by Lowentwickler** [comment]
![Snímek obrazovky z 2022-06-25 16-45-06](https://user-images.githubusercontent.com/5078803/175778666-54f8d1cc-9dbc-4fc7-8908-667f83abd9e1.png)

```
<MapContainer...>
      <FullScreenControl />
</MapContainer...>
```

The code of FullScreenControl component:
```
import L from 'leaflet'
import { createControlComponent } from '@react-leaflet/core'
import 'leaflet.fullscreen'
import 'react-leaflet-fullscreen/dist/styles.css'

function createFullScreenControl(props) {
  const instance = L.control.fullscreen(props)
  instance.
}

const FullScreenControl = createControlComponent(createFullScreenControl)

export default FullScreenControl

```

**Comment by PaulLeCam** [comment]
@Lowentwickler please open a dedicated issue with a running example.

**Comment by tbowmo** [comment]
@PaulLeCam

I tried 4.0.1, but the problem persists, context is still null, when entering the useEffect cleanup upon unmount, (singlestepping through the code in debug mode)

**Comment by PaulLeCam** [comment]
It's not according to my tests, adding logs to Leaflet's `map.remove()` shows the call is successfully made, so I won't investigate this further.
If you still have issues, this might be specific to your code rather than the library.

**Comment by barbalex** [comment]
I have an app that has been using react-leaflet forever.

Recently I have code-split the app to reduce the size of the js conde needed for first render.
To do this I have loaded the most important components using React.lazy (https://reactjs.org/docs/code-splitting.html#reactlazy).

Nothing else was changed.

Since then we regulary see the "Map container is already initialized" error.

Seems to me that something must be happening that prevents react-leaflet from running `map.remove()`.
